### ISSUE TITLE
Suggestions 

### ISSUE THREAD

**Issue by TheBalkanDev** [Muqsit/VanillaGenerator#22]
**Can you add Structures like vanilla villages plz. The MultiWorld Team donˋt want to work on the generation.
I’ve tried but... well Lagg ass.

**Comment by Muqsit** [comment]
That is unfortunately beyond the scope of this plugin, which is a 1-1 port of GlowstoneMC's generator.

**Comment by thebigsmileXD** [comment]
@TheBalkanDev I planned to create a plugin that can generate structures from vanilla files (.mcstructure using https://github.com/thebigsmileXD/libstructure) but at the moment i am stuck because those files have some blocks + blockstates with java blockids/blockstates and i do not have a conversion table. I will notify you on this repo if and when i start working on it.
